name = "markov"
version = "0.1.0"
defaultTargets = ["markov"]

[[lean_lib]]
name = "Markov"

[[lean_exe]]
name = "markov"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.27.0-rc1"

[[require]]
name = "LeanSearchClient"
scope = "leanprover-community"
